colors:
  bright:
    black: '#7d8294'
    blue: '#9dbec5'
    cyan: '#ccd4e4'
    red: '#cadcd4'
    magenta: '#e98488'
    green: '#ebbaab'
    white: '#ebedec'
    yellow: '#e9d7be'
  normal:
    black: '#7d8294'
    blue: '#9dbec5'
    cyan: '#ccd4e4'
    red: '#cadcd4'
    magenta: '#e98488'
    green: '#ebbaab'
    white: '#ebedec'
    yellow: '#e9d7be'
  primary:
    background: '#37404d'
    foreground: '#ebedec'
cursor:
  unfocused_hollow: true
env:
  TERM: alacritty
font:
  size: 14.0
live_config_reload: false
scrolling:
  history: 10000
  multiplier: 1
window:
  class:
    general: Alacritty
    instance: Alacritty
  gtk_theme_variant: None
  padding:
    x: 9
    y: 8
  title: Alacritty
