# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#37404d'
foreground='#ebedec'
cursor='#ebedec'

# Colors
color0='#7d8294'
color1='#ebbaab'
color2='#cadcd4'
color3='#e9d7be'
color4='#9dbec5'
color5='#e98488'
color6='#ccd4e4'
color7='#ebedec'
color8='#7d8294'
color9='#ebbaab'
color10='#cadcd4'
color11='#e9d7be'
color12='#9dbec5'
color13='#e98488'
color14='#ccd4e4'
color15='#ebedec'
