#! /bin/sh

bspc monitor -d I II III

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

bspc config border_width 3
bspc config window_gap 20
bspc config active_border_color '#323d43'

bspc config top_padding 2
bspc config -d I top_padding 38
bspc config -d II top_padding 38
bspc config -d III top_padding 38
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a Thunar follow=on
bspc rule -a Wrapper-2.0 state=floating
bspc rule -a MPlayer state=floating
bspc rule -a Xfce4-settings-manager follow=on state=tiled
bspc rule -a Xfce4-notes state=floating rectangle=500x500+1250+100
bspc rule -a Zathura state=tiled
